modificacion del main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,14 +22,13 @@ jobs:
           python-version: 3.9
 
       - name: Install dependencies
-        run: pip install -r requirements.txt
+        run: pip install pytest openai dotenv asyncio supabase
 
-      - name: Run tests
-        run: pytest
-
-      - name: Check test status
-        run: |
-          if ( ${{ job.status }} == 'failure' ); then
-            echo "Los tests han fallado. No se permite el push."
-            exit 1
-          fi
+      - name: Run pytest
+      	run: |
+         pytest
+         exitcode=$?
+         if [ $exitcode -ne 0 ]; then
+          echo "Tests failed. Aborting push."
+          exit $exitcode
+         fi
